### ISSUE TITLE
MenuButton: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by smathson** [reach/reach-ui#194] opened 2019-06-08 03:58 UTC
Encountering an issue with MenuButton throwing a `Cannot read property 'focus' of undefined` error after hovering with the mouse, moving the mouse out of the Menu and then hitting the up arrow on the keyboard. The same error is not thrown when hitting the down arrow. The issue is observable in the current docs. Gif attached.

![ReachMenuFocusError](https://user-images.githubusercontent.com/932981/59141706-d8e3fb80-8966-11e9-9462-417b1a6a2c91.gif)

**Comment by smathson** [comment] 2019-06-08 04:18
My initial investigation looks like the issue is caused here:
https://github.com/reach/reach-ui/blob/master/packages/menu-button/src/index.js#L391

After the blur `state.selectionIndex` is already -1 so the `if (nextIndex !== -1)` block is called with `nextIndex = -2`.

Happy to submit a PR, I'm just not sure what the intended behavior should be. When no item is selected and the user hits the up arrow which item should be selected? The first item? I don't see any specific rules in the ARIA guidelines governing this case but:

> When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item.

...would seem like the most relevant rule.

**Comment by qoalu** [comment] 2019-06-12 09:39
Checked what the logic on Chrome dropdown is:

![Jun-12-2019 11-38-152](https://user-images.githubusercontent.com/1624045/59340610-9cb5ef80-8d06-11e9-998a-5cc41f0e40d9.gif)

Moving mouse anywhere resets keyboard control to initial state

**Comment by smathson** [comment] 2019-08-02 02:15
Cool. @ryanflorence would you accept a PR that implements the above behavior to fix the issue?

**Comment by ReasonableDeveloper** [comment] 2019-08-14 01:15
I'm having the same issue in a test using jest + react testing library.

Unfortunately, I wasn't able to reproduce this issue in a codesandbox yet. In my tests I'm simply getting the `MenuButton` by it's data attribute and clicking it via `fireEvent.click(menuButton)`. This only happens sometimes as one test that is doing the exact same thing is working fine 😕

**Comment by mdgozza** [comment] 2019-08-29 04:54
@ReasonableDeveloper I am having the exact same issue as you with react-testing-library

**Comment by ReasonableDeveloper** [comment] 2019-09-03 13:49
My failed attempt of reproducing the error in a codesandbox can be found [here](https://codesandbox.io/s/reach-ui-github-issue-cb3wf)

Unfortunately, all the tests are passing in the codesandbox but failing in my project. At this point, I'm uncertain if the problem is related to jsdom, reach-ui or react-testing library.

**Comment by kendallgassner** [comment] 2019-09-04 20:06
I put up a pull request: https://github.com/reach/reach-ui/pull/266

**Comment by kendallgassner** [comment] 2019-09-06 16:42
also @CodingDive to temporally fix your tests until my pull request is merged you can add something like this to mock the requestAnimationFrame. I hate adding timeouts and this is just  a "bandaid  solution" but it works for now. 

```
  beforeEach(() => {
    jest.spyOn(window, 'requestAnimationFrame').mockImplementation(cb => {
      return setTimeout(cb, 200);
    });
  });

```

**Comment by randallagordon** [comment] 2019-09-13 21:51
I can repro in @CodingDive's sandbox by:

1. Clicking to open the `MenuButton`
2. With the cursor inside the `MenuList`, use any arrow keys
3. Move the cursor over a `MenuItem` and away such that no items are selected
4. Move the cursor outside the `MenuList` and hit the _up_ arrow key again (seems to be up only?)
5. 💥

**Closed** 2019-10-15 15:21 UTC
Labels: enhancement
