### ISSUE TITLE
Dialog: screen jumps after closing animated dialog

### ISSUE THREAD

**Issue by eahlberg** [reach/reach-ui#113] opened 2019-01-28 12:18 UTC
When I try to use the Dialog component in combination with Transition from react-spring (version 7), the screen jumps to the original position after closing the dialog. I'm using Chrome v71.

I've put together an example [here](https://codesandbox.io/s/v5z5jol3l) which shows the issue. I've adapted the example to the updated react-spring API to the best of my ability. To reproduce:
1. Open the dialog
2. Quickly scroll to the bottom
3. See the screen jump

I'm open to helping out, but I'm unsure where to start and even if this is a reach-ui or react-spring issue. Might also be related to https://github.com/reach/reach-ui/issues/98 and https://github.com/reach/reach-ui/issues/3?

**Comment by eahlberg** [comment] 2019-01-28 12:20
It does not seem to be an issue on Safari.

**Comment by bradwestfall** [comment] 2019-10-01 23:52
@eahlberg I wasn't able to see the error visually with Chrome on Mac. Can you verify if this is still an issue and if so, maybe provide a gif

**Comment by chancestrickland** [comment] 2019-10-10 21:56
I cannot reproduce this with the example provided. @eahlberg if you continue to experience this with the latest version, let us know and maybe provide a screen capture to help us debug. I'll close this for now.

**Closed by chancestrickland** 2019-10-10 21:56 UTC
Labels: potential-bug
