### ISSUE TITLE
[MenuButton] Long menu causes window to scroll and click on item

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#563] opened 2020-04-27 08:47 UTC
### Current Behavior

If the items of MenuButton exceed the window height, the window becomes scrollable. Then, opening the menu would scroll the window, and sometimes click on the option that falls under the cursor

### Expected behavior

MenuButton should not click on the option? Idk. Is scrolling expected?

### Reproducible example

https://codesandbox.io/s/long-thunder-ilwv4?file=/src/App.js

**Comment by raunofreiberg** [comment] 2020-04-27 08:50
Here's a quick gif of what happens when I tried to use MenuButton with a long list of options. The Menu closes instantly after being opened:

![gif](https://i.gyazo.com/806b62446a3202a4228520d506e7128a.gif)

<hr />

I threw a `max-height` with an `overflow-y: auto` on there, because I don't see a use case for such a massive menu, and this fixed it. But I think this is a bug nonetheless.

**Comment by chancestrickland** [comment] 2020-04-28 05:09
This is a known issue, but I'm not sure if we should deal with it directly. I think you would definitely want to use an overflow, but you might also want to implement a custom scroll button with the `position` prop in `MenuPopover`. My opinion is that this is best left for individuals to implement.

If you were to run into any issues or barriers in customization, then we'd need to examine the API a bit to see how we could work around that.

**Comment by raunofreiberg** [comment] 2020-04-28 08:26
I don't think we should deal with the scrolling issue. That I agree, should be up to the developer. Although, I find it a bit odd that the "open menu" click would then also select an item in the menu, and close it as a result. Could we do something about that?

**Comment by smeijer** [comment] 2020-08-20 12:18
Can this be reopened? It's still an issue in the latest version.

**Comment by smeijer** [comment] 2020-10-06 09:00
@chaance, I suggest adding `Status: Consideration` to the `exemptLabels` :sweat_smile: 

https://github.com/reach/reach-ui/blob/51e163dcfc2b3654e5344b719398daa3775cab63/.github/stale.yml#L6-L12

**Comment by thiniulian** [comment] 2020-10-27 13:37
Hello! 
I also have this issue, exactly as described by the @raunofreiberg. 
The scrolling is annoying but we can live with it (some pointers on how to disable/go around it would be much appreciated).
The auto click in turn is truly unwanted, and it's not necessarily happening on long menus, it's enough if you have a resized window and the height of the dropdown is larger than the window height.

**Comment by indiesquidge** [comment] 2020-11-25 20:17
@thiniulian the auto click is still an issue you're saying? I'm not able to reproduce it (I used [this sandbox][1] from #692 with the default `<MenuList>` since @raunofreiberg reproducible example breaks on a TypeError for me.)

Related conversation around the auto-scroll behavior: https://github.com/reach/reach-ui/pull/692

[1]: https://codesandbox.io/s/gallant-bassi-p9tx0

**Comment by DispatchCommit** [comment] 2021-01-28 08:37
@indiesquidge I can reproduce the bug with your code sandbox link.

![reach-ui-bug](https://user-images.githubusercontent.com/45262335/106110022-0c0c6d00-60ff-11eb-9e6f-797c5927b654.gif)

I came up with a workaround by adding a timeout threshold requirement to disable event propagation within a short period, but because of how reach-ui handles it's event flow, it's possible to trigger the `onSelect` function on just mouseUp when your mouseDown starts on a `menu-button`

This causes issues when animating a menulist and it initially appears under the cursor as 1 click can both open the popover menu *and* trigger an action in that menu. In our case, it caused erroneous deletions.

example: 

 
![reach-ui-bug-lbry](https://user-images.githubusercontent.com/45262335/106111320-be90ff80-6100-11eb-879e-547988ba1924.gif)

 
 I suppose the solution to this is to just animate differently, which can be done, but this still seems like broken behavior when the first example for animations is a slide down animation.
 
 but here's an example of how you would have to animate it to prevent this weird mouse event issue that makes 1 click seem like 2 clicks:
 
 
![better-dropdown](https://user-images.githubusercontent.com/45262335/106111414-d5cfed00-6100-11eb-812d-5f4c65dedefa.gif)

there's more information available in the issue linked above: lbryio/lbry-desktop#5416

**Comment by DispatchCommit** [comment] 2021-01-28 08:46
Compare the behavior seen and demonstrated above to a UI framework like vuetify: https://vuetifyjs.com/en/components/menus/#use-in-components

Notice how vuetify's menus can render under the cursor and don't incorrectly trigger a function in the popup menu? That's how I would *expect* the behavior to be. 

It does not seem correct to me that a mouse down event can trigger an action, and then moments later, the mouse up event can *also* trigger an action. 2 clicks for 1 mouse click is a poor user experience.

**Comment by ibenilsen** [comment] 2021-07-14 22:19
I am also experiencing the issue where, if the menu is rendered in the same location as (on top of) the trigger, an item will be instantly selected and close the menu.

**Comment by chaance** [comment] 2021-07-14 23:32
@ibenilsen Can you share a sandbox reproduction? Here is a copy of @raunofreiberg's original issue but with updated versions of React and `@reach/menu-button`, and the instant selection isn't an issue AFAICT. Selection should only happen if the pointer is moved before `mouseup`, which is designed to mirror the behavior of most native dropdowns on macOS.

**Comment by ibenilsen** [comment] 2021-07-14 23:56
I have an instance where the menu appears on top of the trigger. Perhaps this is not a supported use-case? It is very noticeable that it will cause unintentional triggers when doing this. 

Here is a sandbox where I've added some CSS to make this happen: 
https://codesandbox.io/s/blissful-euclid-7r3d9?file=/src/styles.css

**Comment by chaance** [comment] 2021-07-15 00:02
@ibenilsen What environment are you running? Tested your re-pro in Chrome, Firefox and Safari via macOS and it works as expected.

**Comment by ibenilsen** [comment] 2021-07-15 00:05
macOS Chrome, it does work as you described which is why I thought maybe this just isn't supported. However, for me it is very easy to move the mouse prior to 'mouseup', maybe because I'm on a trackpad?  Also maybe try clicking in and out a couple of times.

**Comment by chaance** [comment] 2021-07-15 00:12
Got it, I hear what you're saying. Maybe *any* mouse move is a little too sensitive. Played with some native dropdowns a bit more with the trackpad and it seems like you have to move the pointer more than a few pixels OR wait ~200-300 milliseconds before it enables selection. Would be really cool if the specs for these interactions were documented somewhere 😅

**Comment by ibenilsen** [comment] 2021-07-15 00:41
Agreed, a slight delay seems preferable. Thanks for the investigation.

**Comment by chaance** [comment] 2021-07-15 00:42
@ibenilsen Can you try this and see if it feels a bit better? https://codesandbox.io/s/mouse-moving-e1fc4

**Comment by ibenilsen** [comment] 2021-07-15 01:08
Nice, that handles much better. 

Might suggest going with 500ms to be safe for slow clickers / tappers.

**Closed** 2021-07-15 01:29 UTC
Labels: Status: Consideration, Type: Enhancement
