### ISSUE TITLE
[menu-button] Incorrect left collision when MenuList is wide

### ISSUE THREAD

**Issue by mrm007** [reach/reach-ui#460] opened 2020-02-06 03:37 UTC
### Current Behavior

Same behavior described in #189. It looks like my patch didn't make it into the [new repo](https://github.com/reach/reach-ui/blob/master/packages/popover/src/index.tsx#L157). This is disappointing after waiting for four months to have a stinking one-liner merged in. I already followed this guy's advice https://twitter.com/ryanflorence/status/1139552733029998592.

### Expected behavior

See original issue #189.

### Reproducible example

[This sandbox](https://codesandbox.io/s/lively-cloud-y5kz5) has the latest `menu-button` (0.8.0) and the originally patched 0.1.17 showing the correct behavior.

### Suggested solution(s)

The one-liner from my original patch.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  menu-button  |   0.8.0  |
| React            | irrelevant | irrelevant |
| Browser          | irrelevant | irrelevant |
| Assistive tech   | irrelevant | irrelevant |
| Node             | irrelevant | irrelevant |
| npm/yarn         | irrelevant | irrelevant |
| Operating System | irrelevant | irrelevant |

**Comment by chancestrickland** [comment] 2020-02-07 23:11
We started using the `@reach/popover` module for Menu Button a while ago and it wiped out your merge, so sorry for the oversight in this regression!

I'll get this patched, but for future reference because we are using the Popover component you can pass your own `position` prop into `MenuPopover` and make any changes to the positioning logic you want. So no need to fork, copy paste or do any of that other annoying stuff if you need some specific overrides here!

**Comment by chancestrickland** [comment] 2020-02-08 00:44
Fixed in 0.8.2.

**Closed by chancestrickland** 2020-02-08 00:44 UTC
Labels: bug

**Comment by mrm007** [comment] 2020-02-09 23:13
Thanks @chancestrickland, that was quick! I now realise my tone was a bit rough, and I apologise for that.

**Comment by chancestrickland** [comment] 2020-02-10 17:52
No sweat, and no offense taken. 🤝
