### ISSUE TITLE
Allow `null` children in MenuList

### ISSUE THREAD

**Issue by tmcw** [reach/reach-ui#236] opened 2019-07-19 21:42 UTC
Right now MenuList has a strong rule that all children must be either MenuItem or MenuLink. This makes the API pretty tricky if you have any variation in your UI, like

```js
<MenuList>
    {(logic.canUnpublish(user, notebook) ||
      logic.canUnshare(user, notebook)) && (
      <MenuItem
        key="4"
        onSelect={async () => {
          await api.documentUnpublish(notebook.id);
          reload();
          closeMenu();
        }}
        className={`${buttonClass} hover-near-black`}
      >
        <UnshareIcon className="mr2" />
        {logic.notebookStatus(notebook) === "public"
          ? "Unpublish"
          : "Disable link sharing"}
      </MenuItem>)}
</MenuList>
```

In the case that this is `false`, MenuList crashes because it encounters an invalid child. The same if you have a ternary condition and have some things be `null` if they aren't relevant to that view. Ideally, MenuList is more relaxed.

Likewise, we have menus with dividers in them: `<div>` elements with borders that keep items away from each other in meaningful groups. Those dividers aren't, and probably shouldn't be, clickable, and they also shouldn't participate in keyboard shortcuts.

**Comment by venikx** [comment] 2019-07-26 14:45
Hi @tmcw 

The first part indeed seems like a bug. I'm working on it right now I can reproduce it. 
Not sure what you mean with the second part of the issue:

> Likewise, we have menus with dividers in them: `<div>` elements with borders that keep items away from each other in meaningful groups. Those dividers aren't, and probably shouldn't be, clickable, and they also shouldn't participate in keyboard shortcuts.

I tried adding a `<hr />` in between two `<MenuItem />`'s, but it seems to render what I expect it to render. Could you provide an example clarifying it further?

**Comment by tmcw** [comment] 2019-07-29 19:43
Non-MenuItem components will render, but they crashed on hover or if you try to use keyboard shortcuts to navigate the Menu, because reach-ui will [attempt to call .focus() on them](https://github.com/reach/reach-ui/blob/master/packages/menu-button/src/index.js#L49), a method that will not exist for all types.

**Comment by venikx** [comment] 2019-07-29 23:11
I’ll try the keyboard navigation in the PR I’ve created, but elements that aren’t focusable were handled already based on the things I tried in Storybook. I’ll double check the coming week or so though.

**Comment by venikx** [comment] 2019-07-30 18:04
@tmcw I can't reproduce what you are referring to. Non-menu items which don't have the capability to focus are getting filtered out here: https://github.com/reach/reach-ui/pull/241/files#diff-13ae4985661da7cf08440d52edf169faL347. Any other element than those two elements are not interactive via the keyboard. 

What you are describing sounds a lot like the issue I fixed in this PR: https://github.com/reach/reach-ui/pull/241, because the property `type` of undefined and null doesn't exist.

**Comment by chancestrickland** [comment] 2019-10-09 18:25
I believe this should be addressed in https://github.com/reach/reach-ui/pull/266, but if you still have issues with the latest alpha release let me know and I can investigate further.

**Closed by chancestrickland** 2019-10-09 18:25 UTC
Labels: potential-bug
