### ISSUE TITLE
Menu-Button Display Issues with Styled-Components

### ISSUE THREAD

**Issue by SCasarotto** [reach/reach-ui#393] opened 2019-11-26 21:31 UTC
### Current Behavior
When MenuButton is wrapped with styled Components this occurs. Each item is not highlighted separately. See Codesandbox example.
![image](https://user-images.githubusercontent.com/13336976/69674009-9a074680-1069-11ea-8cce-4bd4cf9f0f2e.png)

### Expected behavior
When no styled are applied but styled-components are used to wrap the component, nothing should change from base behavior.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/small-silence-l3ifb)

### Suggested solution(s)
 Not sure. In the docs it says "You should be able to style Reach UI components like any other element in your app. If not, report a bug!" so I thought I would report.

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| **[REACH_PACKAGE_NAME]** | 0.6.2 
| React                    | 16.12.0
| Browser                  | Chrome
| Assistive tech           | none
| Node                     | n/a
| npm/yarn                 | yarn
| Operating System         | MacOSX

**Comment by stephan281094** [comment] 2019-11-29 19:46
You can use the `as` attribute to pass in the styled component. Check out the example [here](https://github.com/reach/reach-ui/blob/master/packages/menu-button/examples/styled.example.js).

**Comment by viridia** [comment] 2019-11-30 04:55
I'm having the exact same issues when styling with emotion.

It appears that all of the menu items have the `data-selected="true"` attribute. This doesn't seem right.

**Comment by stephan281094** [comment] 2019-11-30 15:46
@viridia You can do the following:
```jsx
import styled from "@emotion/styled";
import { MenuItem } from "@reach/menu-button";

const StyledItem = styled.div`
  &[data-selected] {
    background: palevioletred;
  }
`;

<MenuItem as={StyledItem} onSelect={action("Download")}>
  Download
</MenuItem>;
```

Notice we're doing `as={StyledItem}` in order to get the desired styles.

**Comment by chancestrickland** [comment] 2019-12-01 15:26
Duplicate of https://github.com/reach/reach-ui/issues/119. FYI I have a PR open that will address this, so stay tuned in the other issue for an update when we get this patched (hopefully in the next release)

**Closed by chancestrickland** 2019-12-01 15:26 UTC
Labels: duplicate
