### ISSUE TITLE
Weird CSS behaviour with the dialog

### ISSUE THREAD

**Issue by mikecousins** [reach/reach-ui#261] opened 2019-08-23 17:08 UTC
I'm trying to migrate our modals over to reach dialogs and I'm running into some weird css bugs.

Here is how my page looks after switching. It's got a grey background:
![image](https://user-images.githubusercontent.com/725614/63610228-2c450d80-c596-11e9-8a0b-868c19dfaa1b.png)

If I turn off the background I get a white background:
![image](https://user-images.githubusercontent.com/725614/63610258-4121a100-c596-11e9-9da2-3543a36f6d1b.png)

If I remove position: fixed from the background, a bunch of the modal disappears and the body height becomes half of the view height:
![image](https://user-images.githubusercontent.com/725614/63610287-5696cb00-c596-11e9-9312-890ba5061166.png)

Any ideas?

**Comment by christiankaindl** [comment] 2019-08-28 08:16
Could you provide a code sample?

Otherwise it's hard to guess what could be the issue. What do you mean by "turn off the background"? Does that mean you set it to `transparent`?

Something else that might be a possibility: Do you include the Dialog default styles? They can be found here: https://github.com/reach/reach-ui/blob/master/packages/dialog/styles.css

And general Reach UI styling guide is available here: https://ui.reach.tech/styling/

**Comment by venikx** [comment] 2019-10-01 23:32
@christiankaindl Does this sound like a reasonable explanation why it might happen in your case as well?

**Comment by christiankaindl** [comment] 2019-10-02 06:46
@venikx I am not having this issue, that's @mikecousins ^^

I don't think it is a layering issue. The default style for the backfrop is a transparent grey, so the stuff behind the modal should be visible. Maybe there is just a missing or overridden style by accident.

But without having insight into his code (or a reproducable Codesandbox) it's very hard to see what would cause this particular issue. E.g. Where does the inspector show the content that should be visible hehind the modal?

**Comment by mikecousins** [comment] 2019-10-02 17:13
@christiankaindl Here's a quick sandbox I made. It's really funky and I don't quite understand what's happening.

https://codesandbox.io/s/frosty-sun-hoouw

With the dialog in place, in code sandbox it shows the dialog with a pure grey background:
![image](https://user-images.githubusercontent.com/725614/66065763-62669d00-e505-11e9-8249-5e023a838a15.png)

If you click view in new tab it shows the same thing:
![image](https://user-images.githubusercontent.com/725614/66065814-79a58a80-e505-11e9-8db2-c5d03bbd1b29.png)

If you remove the dialog you get a white screen in code sandbox:
![image](https://user-images.githubusercontent.com/725614/66065845-8a560080-e505-11e9-9275-8c08f09816a8.png)

If you click view in new tab though it works fine:
![image](https://user-images.githubusercontent.com/725614/66065881-99d54980-e505-11e9-962b-26f74409828e.png)

**Comment by venikx** [comment] 2019-10-03 15:08
## Steps to reproduce
1. Click __Show Dialog__
2. Click on either __SideBar__ or __Content__
=> Closes the Modal
3. Click __Show Dialog__
4. Click on either __Header__
=> Nothing happens

## How to fix?
Remove the `z-index: 99` from `.topbar`'s CSS. 

## Why is this happening?
I assume the reason is that the topbar seems to be on top of the Modal, so the Modal can't capture the backdrop click anymore, since the Modal is only supposed to close when the Backdrop itself is clicked.

**Comment by mikecousins** [comment] 2019-10-03 16:57
Whoops, sorry @venikx, I was working on trying to fix it and broke the demo. I have it in more of a normal state now.

I did some more digging and it seems like the root cause is the focus lock stuff that switches the body from `position: absolute` to `position: relative !important`. When that happens all of my content goes away. It seems to be because I have some divs that aren't sized fully up the chain. For now I put in a weird hack that sets the position inline to `absolute !important` after the dialog is mounted, but it's a super gross hack and causes a flash of background content. It seems like one fix would be to not change that style in certain cases (like if it's absolute).

It seems like I could also fix this by rejigging my styling and properly sizing all of the parent elements.

**Comment by venikx** [comment] 2019-10-03 20:30
@mikecousins Not sure if intended and I'm by far not a CSS expert, so I can't really explains why it's happening, but removing the absolute positioning seems to fix it. 
I wonder how 1) absolute positioning works, main you render an element via a portal 2) how it gets affected by fixed positioning (the dialog is using fixed positioning).

**Comment by venikx** [comment] 2019-10-03 21:03
@mikecousins Actually, I made an example using css-grid: https://codesandbox.io/s/thirsty-water-9j567.
TIL Codesandbox is using iframes and has styled the body of the iframe by default, which is why you added the styling on html and body.

**Comment by chancestrickland** [comment] 2019-10-09 18:22
I'm going to close this for now. I don't really know that we can reliably account for layouts where everything is positioned `absolute`. For this particular case you would get a better result by building your layout with grid, flexbox -- or even floats with a tiny bit of JS to calculate your heights.

**Closed by chancestrickland** 2019-10-09 18:22 UTC
Labels: potential-bug
