### ISSUE TITLE
[menu-button] The Popover remains visible at the 4th.

### ISSUE THREAD

**Issue by mrmntte** [reach/reach-ui#651] opened 2020-08-05 19:42 UTC
### Current Behavior

The menu popover does not disappear at the 4th click.
![v](https://user-images.githubusercontent.com/49642108/89454486-62878880-d726-11ea-8f78-7cb0085efdb0.gif)

### Expected behavior

The popover should disappear whenever you click outside the same component.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/nervous-maxwell-zhtze)

### Environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/menu-button     |     0.10.5    |
| React            |         |    16.12.0     |
| Browser          |    Chrome     |    84     |
| Operating System |    macOS     |    Mojave     |

**Comment by raunofreiberg** [comment] 2020-08-07 08:44
Duplicate of https://github.com/reach/reach-ui/issues/566.

**Closed** 2020-08-07 20:13 UTC
