### ISSUE TITLE
props for styling in styled components bleeding through to html (transient props)

### ISSUE THREAD

**Issue by Jimmydalecleveland** [reach/reach-ui#259] opened 2019-08-20 01:10 UTC
Hello, thanks for making this cool package!
This issue isn't particular to reach-ui, but I'm hoping you have some solutions or suggestions of how you'd get around this problem.

When passing a custom prop to a styled version of a reach component (e.g. Tab) for the purpose of styling, the following error occurs:
```js
Warning: React does not recognize the `isBig` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isbig` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(Tab))
    in ForwardRef(Tab) (created by Context.Consumer)
    in StyledComponent (created by Styled(Component))
    in Styled(Component) (at App.js:14)
```

where the code looks like this:
```js
import React from 'react';
import styled from 'styled-components';
import { Tab } from '@reach/tabs';

const MyTab = styled(Tab)`
  ${({ isBig }) => (isBig ? 'padding: 20px' : 'padding: 5px')};
`;

function App() {
  return (
    <div className="App">
      <MyTab type="submit" className="button" isBig>
        Button text
      </MyTab>
    </div>
  );
}

export default App;
```

I realize this is because the prop `isBig` is passed down through the styled component to reach ui's Tab component on line 198 of `@reach/tabs/src/index.js`, in the form of `{...htmlProps}`
```js
  return (
    <Comp
      data-reach-tab=""
      ref={ref}
      role="tab"
      id={`tab:${_id}`}
      tabIndex={isSelected ? 0 : -1}
      aria-selected={isSelected}
      aria-controls={`panel:${_id}`}
      data-selected={isSelected ? "" : undefined}
      onClick={_onSelect}
      children={children}
      // The following fellow
      {...htmlProps}
    />
  );
```

But I am curious if you have a solution to how you would accomplish this, as it seems to be a pretty common use case for any styled component library. It is just a warning (with error highlighting) but it floods my tests and console. Any Ideas?

**Comment by tarang9211** [comment] 2019-08-20 21:14
@Jimmydalecleveland we would need to create some sort of utility function that has a mapping of valid html attributes and sanitizes it.

**Comment by Jimmydalecleveland** [comment] 2019-08-21 14:52
That makes sense, and this is more of a general problem for packages that spread props onto html elements. If you had to get around this as a user of this package, what would be your approach?

Currently I'm making custom components that return the `@reach/tabs` components after stripping off any props I know that I'm passing that shouldn't go through. It's either that or change my styling props to take strings instead and be all lowercase, but that forces a change in the way my components are used and ends up in the rendered html, which I'm not a fan of.

Anyways, thanks for looking at this either way.

**Comment by tarang9211** [comment] 2019-08-28 20:49
@Jimmydalecleveland I think for now you should just write a function that extracts those props so it doesn't throw a warning/error in the console. We should ideally have a way for all components to filter out non-html properties.

**Comment by ebcrowder** [comment] 2019-08-29 01:17
I found that the function referenced [here](https://github.com/styled-components/styled-components/issues/1198#issuecomment-425650423) solved this issue with minimal code:

```javascript
const StyledLink= styled(({ primary, ...props }) => <Link {...props} />)`
  color: ${props => props.primary ? themeColors.primary : 'red'};
`
```
 
It does use a syntax that I have not seen with respect to `styled-components` before, so I am referencing it here in case it can help other folks.

**Comment by GuillaumeAmat** [comment] 2019-09-13 16:40
@ebcrowder Unfortunately it does not solve the issue when using `as` or `forwardedAs`:

```jsx
import { MenuButton } from '@reach/menu-button';
import React from 'react';

const Button = styled(({ primary, ...props }) => <button {...props} />)`
  color: ${props => props.primary ? themeColors.primary : 'red'};
`;

const BlockButton = styled(Button)`
  display: block;
`;

const MyComponent = () => (
  <>
    <Button as={MenuButton} primary={true} />;
    <BlockButton forawardedAs={MenuButton} primary={true} />;
  </>
);
```

In `MyComponent`, both buttons generate React errors because `as` and `forwardedAs` replace the final filtering component: `({ primary, ...props }) => <button {...props} />`.

cc @tarang9211

**Comment by GuillaumeAmat** [comment] 2019-09-14 13:30
A temporary solution could be:

```jsx
import { MenuButton } from '@reach/menu-button';
import React from 'react';

const BreakerButton = styled.button``;

const Button = styled(({ primary, ...props }) => <BreakerButton {...props} />)`
  color: ${props => props.primary ? themeColors.primary : 'red'};
`;

const BlockButton = styled(Button)`
  display: block;
`;

const MyComponent = () => (
  <>
    <Button forwardedAs={MenuButton} primary={true} />;
    <BlockButton forwardedAs={MenuButton} primary={true} />;
  </>
);
```

That way, only `BreakerButton` is cut and the filtering is done one level before in `Button`. The only adaptation to make in existing code is to always use `forwardedAs` instead of just `as` on `Button`.

**Comment by bradwestfall** [comment] 2019-10-01 23:24
Is this a dup of #116 ?

**Comment by danieltott** [comment] 2019-10-21 14:03
@bradwestfall This does not seem to be a duplicate of #116 - this one is about non-valid props getting sent into html elements, #116 is about CSS specificity (not props)

**Comment by chancestrickland** [comment] 2019-11-17 06:09
I'm going to close this since it's really a question about Styled Components and not Reach UI. There is a long-running issue there with several posted workarounds suggested in the comments, though I'm not sure if there's an *official* documented solution or not. https://github.com/styled-components/styled-components/issues/439.

**Closed by chancestrickland** 2019-11-17 06:09 UTC
Labels: question

**Comment by Jimmydalecleveland** [comment] 2020-08-19 18:01
For anyone dealing with this issue in the future, it looks like Emotion has a solve for this now.
https://emotion.sh/docs/styled#customizing-prop-forwarding

I imagine Styled Components has, or will have, something similar. Hope that helps.
