### ISSUE TITLE
Reach Tabs flashes all tab panes when visit the page

### ISSUE THREAD

**Issue by HuyAms** [reach/reach-ui#971] opened 2022-09-20 19:56 UTC
### Current Behavior

There is a flash of all Tab Panels when I first visit the page

https://user-images.githubusercontent.com/26871154/191351851-4418e0d8-7148-4374-8813-07b1316aafe8.mov

### Expected behavior

Only the active tab should be visible

### Reproducible example

Please see the bug in this [Codesandbox](https://codesandbox.io/s/affectionate-chatelet-6gckbv?file=/app/routes/index.tsx:0-32)

Try to hit the refresh button a few times to see the issue
![Screenshot 2022-09-20 at 22 59 30](https://user-images.githubusercontent.com/26871154/191353026-5d162df0-3743-4786-83df-83e1f3856bc7.png)

### Additional context

I think it works well with React but has an issue with [Remix](https://remix.run/)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     @reach/tabs    |   ^0.17.0      |
| React            |     react    |   18.2.0      |
| Browser          |    Chrome     |   105.0.5195.125 (Official Build) (x86_64)      |
| Assistive tech   |         |         |
| Node             |         |     v17.3.1    |
| npm/yarn         |         |   8.3.0      |
| Operating System |    MacOS     |    11.3.1     |

**Comment by theMosaad** [comment] 2022-09-22 11:56
duplicate of https://github.com/reach/reach-ui/issues/907

**Closed** 2022-10-08 17:04 UTC
