### ISSUE TITLE
Tooltip bonanza bug

### ISSUE THREAD

**Issue by bvaughn** [reach/reach-ui#166] opened 2019-05-07 22:08 UTC
Noticed this issue testing the React profiler:
![@reach-tooltip-bug-Kapture 2019-05-07 at 14 52 16](https://user-images.githubusercontent.com/29597/57335776-8f3e9180-70d8-11e9-8a39-a73462e47b23.gif)

Can be reproduced by going [here](https://react-devtools-experimental.now.sh/) and importing [this `profiling.json` export](https://gist.github.com/bvaughn/b6946712957bdcdc3c031ded59bb3c72).

I am working on a smaller repro but haven't yet figured it out. 😅 

Note that this bug occurs in tooltip versions 0.1 and 0.2.

**Comment by bvaughn** [comment] 2019-05-07 22:13
Here's a smaller repro:
https://qkyvl35j09.codesandbox.io/

**Comment by paulconlin** [comment] 2019-05-21 18:52
I've seen this issue a few times in my project as well, though I can figure out the steps to reproduce it as consistently as your example ^

**Comment by FlipgridMartin** [comment] 2019-05-22 14:30
@bvaughn I noticed that the tooltip bug doesn't happen if you remove the Tooltip from the initial `repro` button. Possibly a timing subscriptions issue?

https://codesandbox.io/s/reachtooltip-bonanza-bug-repro-k8fwg

**Comment by bvaughn** [comment] 2019-05-22 15:24
Fair enough, although that's not really an option in my project (DevTools) since that button needs a tooltip as well :)

**Comment by FlipgridMartin** [comment] 2019-05-22 15:38
Totally understand. I was just hinting towards a possible cause for the issue, our team is in the same boat!

**Comment by SavePointSam** [comment] 2019-06-11 22:23
I found a possible solution. Though, I want to make sure that it does not have an unintended side effects before I post a PR.

**Comment by SavePointSam** [comment] 2019-06-11 23:14
@bvaughn, I was able to correct all the tooltips showing upon transition with my WIP solution. However, your demo does shift focus away from and back to the button that was originally clicked (default browser behavior, AFAIK). I added a red outline to the focused element in the GIF below demoing my solution. Is this your desired behavior?

![2019-06-11 16 08 50](https://user-images.githubusercontent.com/8203211/59312947-c407b080-8c63-11e9-8938-9768bc3c911a.gif)

**Comment by bvaughn** [comment] 2019-06-12 14:29
I'm not really sure what you're asking. I don't explicitly set focus, so... it seems like if the browser's default behavior causes tooltips to break, that's not good. (There are a few cases where this happens in DevTools. This was just one repro I was able to isolate.)

**Comment by SavePointSam** [comment] 2019-06-12 15:06
I'm asking what you're expected behavior is. I can see that there is something off, but I'm not sure what you're expected behavior is. Given the patch I've written I would say that it is _almost_ there. As only the focused element is given a tooltip. However, I do think that the element ID assignment could be better as previously used IDs are automatically used again upon the removal of a node with a reserved ID.

So, as it stands right now. I'm not sure what should be done, @ryanflorence.

**Comment by bvaughn** [comment] 2019-06-12 15:11
Gotcha.

> I'm asking what you're expected behavior is.

My expectation is just that every tooltip won't show at once. I don't actually have much of an expectation about whether the single tooltip would show (or not) on return focus. Slight preference for "not" but I can understand if this would be difficult to achieve.

**Comment by SavePointSam** [comment] 2019-06-12 15:33
> My expectation is just that every tooltip won't show at once.

If that is the case, then I believe my patch will address that. I suppose I'll just post a PR and we can continue from there.

**Comment by paulconlin** [comment] 2019-06-13 15:24
Thanks for digging in @SavePointSam! This is a bug that would prevent us from using it in production, but we love it otherwise. Hopefully we can hear back soon from Ryan if he's ok with your solution.

**Comment by ryanflorence** [comment] 2019-06-14 15:24
I'll take a look at this today, thanks everybody :)

**Comment by ryanflorence** [comment] 2019-06-14 15:26
Also, just noticed the name of this issue, @bvaughn you crack me up 😂

**Comment by SavePointSam** [comment] 2019-06-18 20:05
@ryanflorence any plans to merge my fix soon?

**Comment by paulconlin** [comment] 2019-06-19 16:04
Looks like the fix is in 0.2.2! Thanks so much @ryanflorence  and @SavePointSam , this will be going out to some very happy users (and devs) in the next month. Our previous tooltip implementation was a mess.

**Comment by bvaughn** [comment] 2019-06-19 16:05
Thanks Ryan and Sam!

**Comment by SavePointSam** [comment] 2019-06-19 22:03
I believe this can be closed now. 😄🚀

**Closed** 2019-10-01 20:08 UTC
