### ISSUE TITLE
Tooltip stuck when surrounding a disabled button

### ISSUE THREAD

**Issue by MayaUribe** [reach/reach-ui#231] opened 2019-07-11 13:40 UTC
When adding a `Tooltip` on top of a disabled `button`, the Tooltip gets stuck, I'm not sure if I'm missing a setting, here is an example of what I'm doing 😄

```
<Tooltip label="Notifications">
   <button style={buttonStyle} disabled={isDisabled}>
     Click Me
   </button>
</Tooltip>
```

![Screen Recording 2019-07-11 at 03 31 PM](https://user-images.githubusercontent.com/988972/61055575-1a4a4980-a3f2-11e9-8dcc-5d2a39fb610d.gif)

**Comment by balazssagi** [comment] 2019-07-17 15:54
I think it's related to disabled buttons not firing mouse events. As a workaround you can wrap the `button` with an other element.

**Comment by venikx** [comment] 2019-07-28 15:25
Can you send me the browser, version + OS?
At least for me I can't reproduce it on the latest Firefox (Nightly), but I can reproduce it for Google Chrome.

**Comment by audiolion** [comment] 2019-07-29 19:42
> I think it's related to disabled buttons not firing mouse events. As a workaround you can wrap the button with an other element.

sounds right, however wrapping the button in a `div` is not fixing the issue for me in Google Chrome

**Comment by raunofreiberg** [comment] 2019-09-13 08:00
Any workarounds for this? Wrapping the button does not work for me either. This seems like a pretty common use case for Tooltip (indicating disabled button reasoning)

**Comment by raunofreiberg** [comment] 2019-10-09 14:08
@chancestrickland Sorry to ping, but lately I noticed that more attention is being put towards the development of Reach UI, hence I'm wondering if this issue is high in the priority list? Thanks a lot for spending time on this, I really enjoy using Reach as a foundation :)

**Comment by chancestrickland** [comment] 2019-10-09 18:30
@raunofreiberg It's in the backlog but we're working through the issues. I'll update as soon as I've merged. If you could help out with a PR or even a CodeSandbox reproduction that would certainly get it moving faster!

**Comment by raunofreiberg** [comment] 2019-10-10 06:07
@chancestrickland Thanks for the response! I've set up a Codesandbox with a reproduction of the issue -> https://codesandbox.io/s/reach-ui-tooltip-disabled-button-issue-unwi0

**Comment by venikx** [comment] 2019-10-10 10:07
@raunofreiberg @chancestrickland  Confirmed to be broken on Chromium based browsers. On Firefox it doesn't get stuck. Chromium, Google Chrome and Vivaldi are broken.

**Comment by chancestrickland** [comment] 2019-10-11 18:50
I think we're going to punt on this issue for now. We are discussing some options and may reconsider, but ultimately this should probably be addressed by the browsers. I also feel like different use cases may require different behaviors, so in the mean time:

1. If you want to hide the tooltip altogether on disabled buttons, you can either use CSS and set `pointer-events: none` on your disabled buttons, or use `onMouseEnter={event => event.preventDefault()}` on your button component if it is disabled (this will work as soon as @mjackson publishes the latest changes for the next version bump, referencing https://github.com/reach/reach-ui/pull/295/)

2. If you want to show the tooltip regardless of a button's disabled state, you can either
  - wrap the button in a div so the tooltip trigger's events are attached to the div (I'd probably opt for this approach), or 
  - use `aria-disabled` instead of `disabled`, but you'll need to patch a bunch of other behavior for this to work as expected

**Closed by chancestrickland** 2019-10-11 18:50 UTC
Labels: potential-bug

**Comment by krvajal** [comment] 2019-12-02 09:40
@raunofreiberg add a padding of at least 1px to the div. That way the cursor always goes through the div when exiting the button. In you example, it works if you enter the button from the sides
