### ISSUE TITLE
[tooltip]: Allow Tooltip to Become Hidden upon Scroll

### ISSUE THREAD

**Issue by MahmoudMousaHamad** [reach/reach-ui#784] opened 2021-04-15 20:08 UTC
## 🚀 Feature request
Allowing Tooltip to Become Hidden upon Scroll
https://reach.tech/tooltip/ 

### Current Behavior
The current behavior involves the display of a tooltip while scrolling.

### Desired Behavior
The desired behavior involves hiding tooltip while scrolling.

### Suggested Solution
Add prop to enable this feature.
Add a listener on component did mount to listen for scroll events. On scroll change, set a hide state to true to hide the tooltip and only display the children instead. Otherwise, display the tooltip upon hover.

### Who does this impact? Who is this for?
People using ReachUI, specifically people using Tooltip component of ReachUI.

### Describe alternatives you've considered
Switching to another library (react-tooltip).

### Additional context
Maybe later.

**Comment by chaance** [comment] 2021-04-20 21:38
Not entirely sure this is something we need to support. The tooltip already disappears when you scroll if the pointer is no longer in the target element. Do other libraries you've worked with use this behavior? Any precedent you can point to would be helpful.

**Comment by jsg2021** [comment] 2021-04-21 20:42
Additional context: he's using this library to display tooltips on a fixed bar... the page scrolls and to tooltop looks like its attempting to compensate, but the target isn't moving. (within a position fixed element)

**Comment by chaance** [comment] 2021-04-21 22:00
Got it. I imagine this could be fixed with the `position` prop but not sure. A reproduction of the issue would be very helpful!

**Comment by jsg2021** [comment] 2021-04-21 22:18
Here you go: https://codesandbox.io/s/zealous-tharp-rvyxc

**Comment by MahmoudMousaHamad** [comment] 2021-04-21 22:21
https://github.com/wwayne/react-tooltip is a fairly popular library that supports hide on scroll. Prop name is `scrollHide` and you can find its implementation here:
https://github.com/wwayne/react-tooltip/blob/9006d11aa2b64142d8767d9af34ee808f99caf15/src/index.js
Here's a snippet form their code:
```javascript
/**
   * When scroll, hide tooltip
   */
  hideTooltipOnScroll(event, hasTarget) {
    this.hideTooltip(event, hasTarget, { isScroll: true });
  }

  /**
   * Add scroll event listener when tooltip show
   * automatically hide the tooltip when scrolling
   */
  addScrollListener(currentTarget) {
    const isCaptureMode = this.isCapture(currentTarget);
    window.addEventListener('scroll', this.hideTooltipOnScroll, isCaptureMode);
  }

  removeScrollListener(currentTarget) {
    const isCaptureMode = this.isCapture(currentTarget);
    window.removeEventListener(
      'scroll',
      this.hideTooltipOnScroll,
      isCaptureMode
    );
  }
```

**Comment by jsg2021** [comment] 2021-04-21 22:26
> Here you go: https://codesandbox.io/s/zealous-tharp-rvyxc

The root of the issue is the position function we added to account for our offset body element had an error... so not this component's fault.

**Comment by jsg2021** [comment] 2021-04-21 22:34
@chaance the position function is a nice escape hatch. Though, it would be nice to get a ref to the trigger and tooltip elements.

**Comment by chaance** [comment] 2021-04-22 03:40
@jsg2021 Understood, but note you can pass your own refs to those components as well and we compose + forward them along. You can also use `useTooltip` and handle the rendering separately if you want. Were you able to solve the problem on your end?

**Comment by jsg2021** [comment] 2021-04-22 04:26
ah, didn't think about our own refs.  good idea! thanks 😊 I believe we have solved it.

**Closed** 2021-04-22 13:36 UTC
Labels: Status: Awaiting Response, Type: Feature
